rem echo off
git init
git add FocusCheck/App.xaml
git add FocusCheck/App.xaml.cs
git add FocusCheck/ViewModel.cs
git add FocusCheck/Converters/ConverterBase.cs
git add FocusCheck/Converters/MyValueConverter.cs
git add FocusCheck/App.config
git add FocusCheck/MainWindow.xaml
git add FocusCheck/MainWindow.xaml.cs
git add FocusCheck/Properties/AssemblyInfo.cs
git add FocusCheck/app.config
git add FocusCheck/Properties/Settings.settings
git add FocusCheck/Properties/Resources.Designer.cs
git add FocusCheck/Properties/Resources.resx
git add FocusCheck/Properties/Settings.Designer.cs
git add FocusCheck/FocusCheck.csproj
git add FocusCheck.sln
git add .gitignore
